apiVersion: v1
kind: Service
metadata:
  name: resume-sorter-service
  namespace: resume-sorter
  labels:
    app: resume-sorter
spec:
  type: LoadBalancer
  selector:
    app: resume-sorter
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
